### ISSUE TITLE
Title is wrong

### ISSUE THREAD

**Issue by fossfreedom** [linuxmint/lightdm-settings#11]
The title of the window shown is "login window". Not sure what "login" has to do with the settings window.

Suggest the window title be changed to "slick settings" or similar.

Happy to do a PR ... Just need to know what the title should be.

**Comment by mtwebster** [comment]
I dunno, I'd say most of our users neither know, nor care what slick-greeter is - they do generally understand what "Login Window" means.  This has also been the name used for the .desktop file and window title in mdm, which we're replacing - consistency is important.

This is the same as other programs that are intended to fill an expected role, rather than stand on their own - nemo or nautilus as Files, xed or gedit as Text Editor - most of the time, you wouldn't know the actual name of the program you're using unless you go to Help->About in their menus.

**Comment by clefebvre** [comment]
Exactly, this is similar to "Date and Time", "Screensaver" etc... it's a configuration/preference item in your menu, your system settings etc..
