### ISSUE TITLE
Operating Method

### ISSUE THREAD

**Issue by aGnamZer0** [linuxmint/lightdm-settings#26]
Hello,

I'm under a Debian distrib and I installed slick-greeter. It works without problem but I had to configure it in command-lines as the GUI Login Window Setting doesn't appear in my control panel.

Since you made such a great soft, I'm really interested but (perhaps it's just too stupid so you didn't feel the need to explain it) I don't understand how to install your soft. After I downloaded it and extracted it, what am I supposed to do ? Do I have to put it in a specific folder ?

Thank in advance for your reply.

Best ragards,

**Comment by CollinScripter** [comment]
Since you on are a Debian distro, after you have installed the latest version of slick greeter, you can download a deb package for lightdm-settings from [here](http://packages.linuxmint.com/pool/main/l/lightdm-settings/lightdm-settings_1.2.3_all.deb). Install that package and then you can run lightdm-settings in a terminal to open the GUI config utility. It is also under 'Login Window' if you want to open it with whatever application launcher you use.

**Comment by shanmukhateja** [comment]
I believe this issue can be marked as closed for inactivity.
