### ISSUE TITLE
Mouse Cursor Theme named wrongly

### ISSUE THREAD

**Issue by pakro** [linuxmint/lightdm-settings#45]
When I change the cursor theme for the slick greeter I see duplicate entries. When I select them they are actually displaying the correct theme. In the screenshot below you see DMZ-White two times. The first entry is the real DMZ-White. The second one is the cursor theme Bibata Ice. 

I'm acutally not sure if this lightdm-settings problem or the cursor theme meta data is just wrong. The name is correct in the Mouse and Touchpad settings however.

![wrong_cursor_theme_name](https://user-images.githubusercontent.com/8904139/78710425-a3f15e00-7915-11ea-87cc-1b8401f65b42.png)

**Comment by victante** [comment]
I noticed the same problem. I looked at my "cursor.theme" files and it seems that lightdm-settings is not displaying what's in the "Name" line, instead it displays what's in "Inherits", and the majority of these custom cursors all have DMZ as their fallback. 
When changing the Inherits line to be the same as the Name of the cursor, lightdm-settings displays the correct name. It's simple to workaround, but it's a bug nonetheless and I hope it's fixed in the future.

![bibataclassic](https://user-images.githubusercontent.com/46327531/82569685-f5b51700-9b56-11ea-98f8-e3d9f11aa0c8.png)
