### ISSUE TITLE
Sync with the theme/icon set

### ISSUE THREAD

**Issue by tio-trom** [linuxmint/lightdm-settings#53]
Hello,
I can't figure it out how I can make it sync and use the user's theme and icon set. The configs seem to be stored in: `/etc/lightdm/lightdm-gtk-greeter.conf`- but unless the user also selects the theme and icon set from the LIGHTDM Settings they won't be synced with the system's theme.

![2022-09-20_14-31](https://user-images.githubusercontent.com/38043315/191258252-9b3f8c51-5499-4950-8eac-584e9df13f78.png)

At least if there was a config file in the user directory one can write a script to sync the system's theme with the greeter one.

Any help please?

**Comment by clefebvre** [comment]
They don't belong to the same user... there could be multiple users on the OS, the login screen belongs to root, not any user in particular. 

You could write a script which arbitrarily chooses a user's config and overwrites roots, and have that run on login or start sequence, or cron job... 

I'll close the issue since this isn't a bug.
